{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "dd763659-8db0-4df4-be46-1f7a4b89d8f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from dotenv import load_dotenv\n",
    "from typing import List\n",
    "\n",
    "# LangChain & Pydantic Imports\n",
    "from langchain_core.prompts import ChatPromptTemplate\n",
    "from langchain_core.output_parsers import PydanticOutputParser\n",
    "from langchain_google_genai import ChatGoogleGenerativeAI\n",
    "from pydantic import BaseModel, Field, ValidationError\n",
    "\n",
    "# --- NEW: Imports for Search Tools ---\n",
    "from googleapiclient.discovery import build\n",
    "from googlesearch import search"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "64a78e5f-ff5b-4274-82b4-b703449043e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 1. Define Data Schemas (Pydantic Models) ---\n",
    "\n",
    "class EmergingRole(BaseModel):\n",
    "    title: str = Field(description=\"The title of the emerging job role.\")\n",
    "    description: str = Field(description=\"What this role involves and why it's emerging.\")\n",
    "    required_skills: List[str] = Field(description=\"A list of key skills needed for this role.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "4156f0ba-e096-4a57-9720-54e8a1fbbb66",
   "metadata": {},
   "outputs": [],
   "source": [
    "class DomainAnalysis(BaseModel):\n",
    "    domain_overview: str = Field(description=\"A concise, engaging summary of what this domain is about.\")\n",
    "    future_outlook_summary: str = Field(description=\"A 5-10 year projection for this domain, highlighting key trends and disruptions.\")\n",
    "    growth_areas: List[str] = Field(description=\"A list of specific areas projected to see significant growth.\")\n",
    "    emerging_roles: List[EmergingRole] = Field(description=\"A list of new and emerging job roles in this domain.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "6760d021-7b93-4e5d-b30b-a4fc000f67cd",
   "metadata": {},
   "outputs": [],
   "source": [
    "class LearningStep(BaseModel):\n",
    "    step: int = Field(description=\"The sequential number of the learning step.\")\n",
    "    title: str = Field(description=\"A clear and descriptive title for this learning step.\")\n",
    "    type: str = Field(description=\"The type of learning content, e.g., 'reading', 'video', 'project'.\")\n",
    "    content: str = Field(description=\"For 'video' or 'reading', a concise topic suitable for a web search. For 'project', a brief description of the project.\")\n",
    "\n",
    "class LearningPath(BaseModel):\n",
    "    path: List[LearningStep] = Field(description=\"The full list of structured learning steps.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "10f44cc3-e2fd-4966-95bc-3beec44e215a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# --- 2. The Career Counselor Agent ---\n",
    "\n",
    "class CareerCounselorAgent:\n",
    "    \"\"\"An AI agent that provides career analysis and learning paths using external tools.\"\"\"\n",
    "\n",
    "    def __init__(self):\n",
    "        \"\"\"Initializes the agent, AI model, processing chains, and search tools.\"\"\"\n",
    "        print(\"🤖 Initializing Career Counselor Agent...\")\n",
    "        \n",
    "        load_dotenv()\n",
    "        if \"GOOGLE_API_KEY\" not in os.environ or \"YOUTUBE_API_KEY\" not in os.environ:\n",
    "            raise ValueError(\"🔴 CRITICAL: GOOGLE_API_KEY and YOUTUBE_API_KEY must be set in a .env file.\")\n",
    "\n",
    "        self.model = ChatGoogleGenerativeAI(model=\"gemini-1.5-flash\", temperature=0.7)\n",
    "        self.youtube_service = build('youtube', 'v3', developerKey=os.environ[\"YOUTUBE_API_KEY\"])\n",
    "        \n",
    "        self._create_chains()\n",
    "        print(\"✅ Agent is ready.\")\n",
    "\n",
    "    def _search_youtube_video(self, query: str) -> str:\n",
    "        \"\"\"Searches YouTube for a video and returns the top result's URL.\"\"\"\n",
    "        try:\n",
    "            search_response = self.youtube_service.search().list(\n",
    "                q=f\"{query} tutorial\",\n",
    "                part='snippet',\n",
    "                maxResults=1,\n",
    "                type='video',\n",
    "                videoDefinition='high'\n",
    "            ).execute()\n",
    "            \n",
    "            if search_response.get(\"items\"):\n",
    "                video_id = search_response['items'][0]['id']['videoId']\n",
    "                return f\"https://www.youtube.com/watch?v={video_id}\"\n",
    "            return \"No relevant video found.\"\n",
    "        except Exception as e:\n",
    "            print(f\"   ⚠️ YouTube API Error: {e}\")\n",
    "            return \"Could not fetch video link due to an API error.\"\n",
    "\n",
    "    def _search_for_article(self, query: str) -> str:\n",
    "        \"\"\"Performs a Google search and returns the top result URL.\"\"\"\n",
    "        try:\n",
    "            search_results = search(f\"{query} article tutorial\", num_results=1, lang=\"en\")\n",
    "            top_result = next(search_results, \"No relevant article found.\")\n",
    "            return top_result\n",
    "        except Exception as e:\n",
    "            print(f\"   ⚠️ Web Search Error: {e}\")\n",
    "            return \"Could not fetch article link due to a search error.\"\n",
    "\n",
    "    def _create_chains(self):\n",
    "        \"\"\"Builds the LangChain Expression Language (LCEL) chains.\"\"\"\n",
    "        analysis_parser = PydanticOutputParser(pydantic_object=DomainAnalysis)\n",
    "        analysis_prompt = ChatPromptTemplate.from_messages([\n",
    "            (\"system\", \"You are a futuristic career analyst... Respond with the requested JSON object...\"),\n",
    "            (\"human\", \"Analyze the career domain: '{domain}'.\\n\\n{format_instructions}\")\n",
    "        ]).partial(format_instructions=analysis_parser.get_format_instructions())\n",
    "        self.analysis_chain = analysis_prompt | self.model | analysis_parser\n",
    "\n",
    "        path_parser = PydanticOutputParser(pydantic_object=LearningPath)\n",
    "        path_prompt = ChatPromptTemplate.from_messages([\n",
    "            (\n",
    "                \"system\",\n",
    "                (\n",
    "                    \"You are an expert curriculum developer... Your task is to create a personalized learning path... strictly following the user's preferred learning style. \"\n",
    "                    \"- If the learning_style is 'visual', you MUST generate a path containing ONLY steps with the type 'video'. \"\n",
    "                    \"- If the learning_style is 'reading', you MUST generate a path containing ONLY steps with the type 'reading'. \"\n",
    "                    \"- If the learning_style is 'practical', you MUST generate a path containing ONLY steps with the type 'project'. \"\n",
    "                    \"Do not mix types...\"\n",
    "                ),\n",
    "            ),\n",
    "            (\"human\", \"Create a learning path for the '{domain}' domain, focusing on these skills: {key_skills}. The user's preferred learning style is '{learning_style}'.\\n\\n{format_instructions}\")\n",
    "        ]).partial(format_instructions=path_parser.get_format_instructions())\n",
    "        \n",
    "        self.learning_path_chain = path_prompt | self.model | path_parser\n",
    "\n",
    "    def get_domain_analysis(self, domain: str) -> DomainAnalysis:\n",
    "        print(f\"\\n🧠 Analyzing the future of '{domain}'...\")\n",
    "        return self.analysis_chain.invoke({\"domain\": domain})\n",
    "\n",
    "    def get_learning_path(self, domain: str, skills: List[str], style: str) -> LearningPath:\n",
    "        print(f\"\\n📚 Generating a '{style}-only' learning path structure...\")\n",
    "        return self.learning_path_chain.invoke({\n",
    "            \"domain\": domain,\n",
    "            \"key_skills\": \", \".join(skills),\n",
    "            \"learning_style\": style\n",
    "        })\n",
    "\n",
    "    def run(self):\n",
    "        \"\"\"Main execution loop for the agent to interact with the user.\"\"\"\n",
    "        print(\"\\n\" + \"=\"*50)\n",
    "        print(\"🚀 Welcome to the Future-Forward Career Planner 🚀\")\n",
    "        print(\"=\"*50)\n",
    "\n",
    "        target_domain = input(\"\\nEnter a career domain you're interested in (e.g., AI in Healthcare): \\n> \")\n",
    "        \n",
    "        print(\"\\nWhat is your preferred learning style? (The path will ONLY contain this type)\")\n",
    "        print(\"  1. Visual (Video tutorials)\")\n",
    "        print(\"  2. Reading (Articles and guides)\")\n",
    "        print(\"  3. Practical (Project-based tasks)\")\n",
    "        \n",
    "        style_map = {\"1\": \"visual\", \"2\": \"reading\", \"3\": \"practical\"}\n",
    "        while (style_choice := input(\"Choose a number (1-3): \\n> \")) not in style_map:\n",
    "            print(\"Invalid choice. Please enter a number from 1 to 3.\")\n",
    "        user_learning_style = style_map[style_choice]\n",
    "\n",
    "        try:\n",
    "            # --- Step 1: Perform Domain Analysis ---\n",
    "            analysis_result = self.get_domain_analysis(target_domain)\n",
    "\n",
    "            if not analysis_result.emerging_roles:\n",
    "                 print(\"\\n⚠️ No emerging roles were identified. Cannot generate a learning path.\")\n",
    "                 return\n",
    "\n",
    "            # --- Step 2: Generate and Process the Learning Path ---\n",
    "            skills_to_learn = analysis_result.emerging_roles[0].required_skills\n",
    "            print(f\"\\n🎯 Identified key skills: {skills_to_learn}\")\n",
    "            \n",
    "            learning_path_result = self.get_learning_path(target_domain, skills_to_learn, user_learning_style)\n",
    "            \n",
    "            print(\"\\n🛠️ Finding the best online resources for you...\")\n",
    "            for step in learning_path_result.path:\n",
    "                if step.type == \"video\":\n",
    "                    print(f\"   -> Searching for a video about: '{step.content}'\")\n",
    "                    step.content = self._search_youtube_video(step.content)\n",
    "                elif step.type == \"reading\":\n",
    "                    print(f\"   -> Searching for an article about: '{step.content}'\")\n",
    "                    step.content = self._search_for_article(step.content)\n",
    "\n",
    "            # --- MODIFICATION: Final, separated printing of the two outputs ---\n",
    "            print(\"\\n\\n\" + \"=\"*25 + \" RESULTS \" + \"=\"*25)\n",
    "\n",
    "            # Output 1: Domain Analysis\n",
    "            print(\"\\n\\n--- 1. DOMAIN ANALYSIS ---\")\n",
    "            print(analysis_result.model_dump_json(indent=2))\n",
    "\n",
    "            # Output 2: Learning Path\n",
    "            print(\"\\n\\n--- 2. PERSONALIZED LEARNING PATH ---\")\n",
    "            print(learning_path_result.model_dump_json(indent=2))\n",
    "            \n",
    "            print(\"\\n\" + \"=\"*59)\n",
    "\n",
    "\n",
    "        except ValidationError:\n",
    "            print(\"\\n🔴 Validation Error: The AI's response did not match the required format. This can happen with very niche domains. Please try a different one.\")\n",
    "        except Exception as e:\n",
    "            print(f\"\\n🔴 An unexpected error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "87df6cd9-f88d-4593-996c-f105fdcc004f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "🤖 Initializing Career Counselor Agent...\n",
      "✅ Agent is ready.\n",
      "\n",
      "==================================================\n",
      "🚀 Welcome to the Future-Forward Career Planner 🚀\n",
      "==================================================\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "\n",
      "Enter a career domain you're interested in (e.g., AI in Healthcare): \n",
      ">  AI in SAAS\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "What is your preferred learning style? (The path will ONLY contain this type)\n",
      "  1. Visual (Video tutorials)\n",
      "  2. Reading (Articles and guides)\n",
      "  3. Practical (Project-based tasks)\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Choose a number (1-3): \n",
      ">  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "🧠 Analyzing the future of 'AI in SAAS'...\n",
      "\n",
      "🎯 Identified key skills: ['Product Management', 'AI/ML knowledge', 'SaaS product lifecycle', 'Data analysis', 'Strategic thinking']\n",
      "\n",
      "📚 Generating a 'visual-only' learning path structure...\n",
      "\n",
      "🛠️ Finding the best online resources for you...\n",
      "   -> Searching for a video about: 'Overview video on AI's role in SaaS products'\n",
      "   -> Searching for a video about: 'Video tutorial on AI-driven product management strategies and techniques'\n",
      "   -> Searching for a video about: 'Animated video explaining core AI/ML concepts for SaaS applications'\n",
      "   -> Searching for a video about: 'Video walkthrough of the SaaS product lifecycle, highlighting AI integration points'\n",
      "   -> Searching for a video about: 'Video tutorial on data analysis techniques and visualizing SaaS performance data'\n",
      "   -> Searching for a video about: 'Video showcasing successful AI strategies in SaaS through case studies and examples'\n",
      "   -> Searching for a video about: 'Video demonstrating the process of building an AI feature for a SaaS product'\n",
      "   -> Searching for a video about: 'Video discussing ethical considerations when implementing AI in SaaS products'\n",
      "   -> Searching for a video about: 'Video exploring future trends and potential applications of AI in the SaaS industry'\n",
      "\n",
      "\n",
      "========================= RESULTS =========================\n",
      "\n",
      "\n",
      "--- 1. DOMAIN ANALYSIS ---\n",
      "{\n",
      "  \"domain_overview\": \"AI in SaaS is a rapidly evolving field that integrates artificial intelligence technologies into software-as-a-service (SaaS) applications. This integration enhances SaaS products with intelligent features, improving efficiency, personalization, and automation for both businesses and end-users.  From predictive analytics to intelligent automation, AI is transforming how SaaS applications are built, deployed, and used.\",\n",
      "  \"future_outlook_summary\": \"Over the next 5-10 years, AI in SaaS will experience explosive growth.  We predict a shift towards more sophisticated AI models, including generative AI and large language models, deeply integrated into core SaaS functionalities.  Expect increased emphasis on explainable AI (XAI) to address transparency and trust concerns.  Hyper-personalization driven by AI will become the norm, and the demand for AI-powered security and ethical considerations will intensify.  The rise of no-code/low-code AI development platforms will democratize access to AI capabilities within SaaS, leading to a surge in innovation from smaller companies and independent developers.\",\n",
      "  \"growth_areas\": [\n",
      "    \"AI-powered customer relationship management (CRM)\",\n",
      "    \"Generative AI for content creation within SaaS platforms\",\n",
      "    \"AI-driven security and threat detection in SaaS\",\n",
      "    \"Personalized learning and adaptive educational SaaS platforms\",\n",
      "    \"AI-optimized SaaS infrastructure and operations (AIops)\",\n",
      "    \"No-code/low-code AI development for SaaS\"\n",
      "  ],\n",
      "  \"emerging_roles\": [\n",
      "    {\n",
      "      \"title\": \"AI-SaaS Product Manager\",\n",
      "      \"description\": \"Leads the strategy and roadmap for AI features within a SaaS product, bridging the gap between AI capabilities and business needs. Requires strong product vision, understanding of AI technologies, and effective communication.\",\n",
      "      \"required_skills\": [\n",
      "        \"Product Management\",\n",
      "        \"AI/ML knowledge\",\n",
      "        \"SaaS product lifecycle\",\n",
      "        \"Data analysis\",\n",
      "        \"Strategic thinking\"\n",
      "      ]\n",
      "    },\n",
      "    {\n",
      "      \"title\": \"AI-SaaS Engineer\",\n",
      "      \"description\": \"Develops and maintains the AI components of SaaS applications. Expertise in machine learning models, cloud infrastructure, and software engineering is crucial.  Focus on integrating AI into existing SaaS architecture and optimizing performance.\",\n",
      "      \"required_skills\": [\n",
      "        \"Software Engineering\",\n",
      "        \"Cloud Computing (AWS, Azure, GCP)\",\n",
      "        \"Machine Learning Engineering\",\n",
      "        \"Model Deployment\",\n",
      "        \"API Integration\"\n",
      "      ]\n",
      "    },\n",
      "    {\n",
      "      \"title\": \"AI Ethics and Governance Specialist (SaaS)\",\n",
      "      \"description\": \"Ensures responsible AI development and deployment within SaaS products. Focuses on mitigating bias, ensuring fairness, transparency, and accountability in AI algorithms.  Collaborates with engineers and product managers to implement ethical AI practices.\",\n",
      "      \"required_skills\": [\n",
      "        \"AI Ethics\",\n",
      "        \"Data Privacy\",\n",
      "        \"Risk Management\",\n",
      "        \"Compliance\",\n",
      "        \"Stakeholder Communication\"\n",
      "      ]\n",
      "    },\n",
      "    {\n",
      "      \"title\": \"Prompt Engineer (SaaS)\",\n",
      "      \"description\": \"Specializes in crafting effective prompts and instructions for large language models (LLMs) used in SaaS applications. Requires deep understanding of LLM capabilities and limitations to optimize AI performance and user experience.\",\n",
      "      \"required_skills\": [\n",
      "        \"Natural Language Processing (NLP)\",\n",
      "        \"Large Language Models (LLMs)\",\n",
      "        \"Prompt Engineering techniques\",\n",
      "        \"AI model evaluation\",\n",
      "        \"User experience design\"\n",
      "      ]\n",
      "    }\n",
      "  ]\n",
      "}\n",
      "\n",
      "\n",
      "--- 2. PERSONALIZED LEARNING PATH ---\n",
      "{\n",
      "  \"path\": [\n",
      "    {\n",
      "      \"step\": 1,\n",
      "      \"title\": \"Introduction to AI in SaaS: A Visual Overview\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=UEHdYNXiIUU\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 2,\n",
      "      \"title\": \"Product Management in the Age of AI: Visual Guide\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=39zbC_PrNQs\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 3,\n",
      "      \"title\": \"Essential AI/ML Concepts Explained Visually\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=FwOTs4UxQS4\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 4,\n",
      "      \"title\": \"SaaS Product Lifecycle: A Visual Journey\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=Fi3_BjVzpqk\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 5,\n",
      "      \"title\": \"Data Analysis for SaaS with Visualizations\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=kgQyvF4gG8E\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 6,\n",
      "      \"title\": \"Strategic Thinking in AI-Powered SaaS: Visual Case Studies\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=Dt6u-yFEpsk\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 7,\n",
      "      \"title\": \"Building an AI-Driven SaaS Feature: A Visual Walkthrough\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=LR-uQxkUJXw\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 8,\n",
      "      \"title\": \"AI Ethics in SaaS: Visual Considerations\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=Tw18-4U7mts\"\n",
      "    },\n",
      "    {\n",
      "      \"step\": 9,\n",
      "      \"title\": \"Future Trends in AI for SaaS: A Visual Forecast\",\n",
      "      \"type\": \"video\",\n",
      "      \"content\": \"https://www.youtube.com/watch?v=ZiNqwpFAx00\"\n",
      "    }\n",
      "  ]\n",
      "}\n",
      "\n",
      "===========================================================\n"
     ]
    }
   ],
   "source": [
    "# --- 3. Run the Agent ---\n",
    "if __name__ == \"__main__\":\n",
    "    agent = CareerCounselorAgent()\n",
    "    agent.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0632f0ec-a015-49d6-aa96-781b02b59ad6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
